app/Controllers/Ambientes.php
app/Controllers/Cursos.php
app/Controllers/Disciplinas.php
app/Controllers/MatrizCurricular.php
app/Controllers/TemposAula.php
app/Controllers/Turmas.php
app/Models/AmbientesModel.php
app/Models/CursosModel.php
app/Models/DisciplinasModel.php
app/Models/MatrizCurricularModel.php
app/Models/ProfessorModel.php
app/Models/TemposAulasModel.php
app/Models/TurmasModel.php

Criando todas as models e controllers

---

app/Views/cadastro-prof.php
package-lock.json

Versão cadastro de professores - sem o css, apenas para teste'

'versao básica - css'

---

app/Views/dashboard.php
app/Views/sys/cadastro-professor.php
app/Views/sys/horarios-professor.php
public/assets/css/modern-vertical/style.css
public/assets/js/form-validation.js
public/assets/js/validacoes/cadastro-professor.js

Ajustes na validação no formulário de cadastro de professores e criação da Tabela de Horários dos professores.

Formulário de cadastro de professores e Tabela de Horários

---

app/Views/dashboard.php
app/Views/sys/horarios-professor.php

Troca de textos por ícones na confirmação na tabela de horários dos professores.

Ajustes na tabela de horário

---

app/Models/AmbientesModel.php
app/Models/CursosModel.php
app/Models/DisciplinasModel.php
app/Models/MatrizCurricularModel.php
app/Models/ProfessorModel.php
app/Models/TemposAulasModel.php
app/Models/TurmasModel.php

Realizado ajuste das 'validationRules' de algumas tabelas, realizado testes apenas dos regex.

Ajustando as 'validationRules'

---

app/Models/AmbienteGrupoModel.php
app/Models/AulaHorarioModel.php
app/Models/AulaProfessorModel.php
app/Models/AulasModel.php
app/Models/GruposAmbientesModel.php
app/Models/HorariosModel.php
app/Models/ProfessorRegrasModel.php
app/Models/VersoesModel.php

Criado novas models com as 'validationRules' definidas.

Novas models com as 'validationRules' definidas

---

app/Config/Routes.php
app/Controllers/AreaTrabalho.php
app/Views/sys/user-desktop.php
public/template/themes/classic-horizontal/pages/ui-features/tabs.html

Foi desmoralizada, mas tá valendo.

Tela inicial usuario

---

README.md
app/Controllers/Professor.php
app/Views/sys/lista-professor.php
app/Views/sys/user-desktop.php

Listagem de professor funcionando perfeitamente. 
by: Luis Henrique.

Listar Professor Rodando Lindíssimo - By: Luis Henrique e Balões de Notificações da Área de Trabalho estilizados by: Paloma Lima

---

app/Config/Auth.php
app/Config/Routes.php

Atualização da função de redirecionamento após login do shield

Atualização do Shield (ajuste dos redirecionamentos)

---

app/ThirdParty/shield-1.1.0/src/Controllers/LoginController.php
app/Views/login.php

Como o outro continuou não funcionando, mudei a abordagem do método. Agora utilizando curl.

Alteração do método do reCaptcha

---

app/Views/importacao_form.php

Integracao da tabela com datatables do template e coluna com checkbox para importar os professores selecionados

---

app/Config/Routes.php
app/Controllers/Ambientes.php
app/Views/sys/cadastro-ambientes.php

Criado Alert para edição de nome do ambiente e mudança no estilo css dos alertas.

Alert para edição de nome do ambiente

---

app/Config/Routes.php
app/Controllers/MatrizCurricular.php
app/Views/components/disciplina/modal-cad-disciplina.php
app/Views/components/matriz/modal-cad-matriz.php
app/Views/components/matriz/modal-deletar-matriz.php
app/Views/components/matriz/modal-edit-matriz.php
app/Views/dashboard.php
app/Views/sys/cadastro-ambientes.php
app/Views/sys/lista-matriz.php

Criação do CRUD da matriz curricular, adicionado links na sidebar e ajustado modal de cadastro da disciplina

CRUD - Matriz, links e cad disciplina

---

app/Config/Routes.php
app/Controllers/Aulas.php
app/Models/AulasModel.php

busca aulas (com informações)

---

app/Controllers/AdminController.php

Ajuste do método de controller para retornar erro em caso de usuário já registrado

---

app/Controllers/Ambientes.php
app/Views/components/grupo-ambientes/modal-add-ambientes.php
app/Views/sys/cadastro-ambientes.php
public/assets/css/custom.css

Botões: efeitos de "acender" ao passar o mouse nos botões de "adicionar ambientes ao grupo" e "listar ambientes do grupo";
Alerts: padronização com os alerts de sucesso das demais páginas;

Ambientes: ajustes nos botões e padronização de alerts

---

public/assets/css/custom.css

Atualização da cor dos itens selecionados no uso do select2 .

---

app/Views/sys/tabela-geral-horarios.php

Ia fazer uns testes mas vi que tava mexendo com o back-end já, então só ajustei o tamanho ai, depois alinhamos o que preciso ajustar aqui. Vou deixar o PR pra analisar antes de fazer o merge.

Ajuste do tamanho da coluna da esquerda

---

.gitignore
app/Views/sys/relatorios.php

Cursos, professores e ambientes com select2 multiple.

Página Relatórios: Atualização de select2 multiple nos filtros.

---

app/Views/sys/professor.php

Por favor, revise antes de aceitar, não quero quebrar o fork principal.

Correção no script da modal de exclusão de professor

---

app/Views/dashboard.php

Reverts leoferrarezi/horarios#154

Revert "Ajuste do collapse gestão de horários (de novo)"
